### ISSUE TITLE
sorry, I try to use this method to remove my pdf's watermark, but error be happened. Can you detail describe the method one again? Here's what I did when I executed the error. Thanks ~~

### ISSUE THREAD

**Issue by MiracleMaker01** [Goshin/Remove-PDF-Watermark#2]
c:\python\Python37-32\Remove-PDF-Watermark-master\src>pdf-watermark-removal.py -s=2 -o=output.pdf abc.pdf
2018-09-13 18:10:05,724 - INFO - Processing page 1/60
Traceback (most recent call last):
  File "C:\python\Python37-32\Remove-PDF-Watermark-master\src\pdf-watermark-removal.py", line 129, in <module>
    main()
  File "C:\python\Python37-32\Remove-PDF-Watermark-master\src\pdf-watermark-removal.py", line 119, in main
    process_page(pdf, i, i < args.skip)
  File "C:\python\Python37-32\Remove-PDF-Watermark-master\src\pdf-watermark-removal.py", line 80, in process_page
    img = Image.frombytes(mode, size, data)
  File "C:\Python\Python37-32\lib\site-packages\PIL\Image.py", line 2368, in frombytes
    im.frombytes(data, decoder_name, args)
  File "C:\Python\Python37-32\lib\site-packages\PIL\Image.py", line 799, in frombytes
    raise ValueError("not enough image data")
ValueError: not enough image data

**Comment by Goshin** [comment]
Seems the PDF file you want to process does not contain any image in the first page. Note that the script can only process scanned documents. If you are sure about that, try to skip the first page in your case.
