### ISSUE TITLE
ValueError: not enough image data

### ISSUE THREAD

**Issue by ovivx** [Goshin/Remove-PDF-Watermark#7]
run then print  ValueError: not enough image data, i am confuse , and can not solve by myself

**Comment by StevenJack1** [comment]
![Uploading image.png…]()

**Comment by StevenJack1** [comment]
$ python3 pdf-watermark-removal.py --output=test.pdf 宪法暑假班讲义-pages-2-10.pdf
2020-10-26 17:44:51,769 - INFO - Processing page 1/9
Traceback (most recent call last):
  File "pdf-watermark-removal.py", line 127, in <module>
    main()
  File "pdf-watermark-removal.py", line 117, in main
    process_page(pdf, i, i < args.skip)
  File "pdf-watermark-removal.py", line 78, in process_page
    img = Image.frombytes(mode, size, data)
  File "/usr/local/lib/python3.8/site-packages/PIL/Image.py", line 2658, in frombytes
    im.frombytes(data, decoder_name, args)
  File "/usr/local/lib/python3.8/site-packages/PIL/Image.py", line 797, in frombytes
    raise ValueError("not enough image data")
ValueError: not enough image data

**Comment by 3DRX** [comment]
same  here
2021-08-06 11:41:35,043 - INFO - Processing page 1/442
2021-08-06 11:42:11,336 - INFO - Processing page 2/442
2021-08-06 11:42:45,503 - INFO - Processing page 3/442
Traceback (most recent call last):
  File "pdf-watermark-removal.py", line 127, in <module>
    main()
  File "pdf-watermark-removal.py", line 117, in main
    process_page(pdf, i, i < args.skip)
  File "pdf-watermark-removal.py", line 78, in process_page
    img = Image.frombytes(mode, size, data)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/PIL/Image.py", line 2735, in frombytes
    im.frombytes(data, decoder_name, args)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/PIL/Image.py", line 810, in frombytes
    raise ValueError("not enough image data")
ValueError: not enough image data

**Comment by Elysium1436** [comment]
Same here.

**Comment by lurenyi4** [comment]
same
(base) PS D:\downloads\Remove\src> python .\pdf-watermark-removal.py --output=output.pdf .\8.pdf
2023-12-27 16:40:36,363 - INFO - Processing page 1/9
Traceback (most recent call last):
  File "D:\downloads\Remove\src\pdf-watermark-removal.py", line 127, in <module>
    main()
  File "D:\downloads\Remove\src\pdf-watermark-removal.py", line 117, in main
    process_page(pdf, i, i < args.skip)
  File "D:\downloads\Remove\src\pdf-watermark-removal.py", line 78, in process_page
    img = Image.frombytes(mode, size, data)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda3\Lib\site-packages\PIL\Image.py", line 2976, in frombytes
    im.frombytes(data, decoder_name, args)
  File "D:\Anaconda3\Lib\site-packages\PIL\Image.py", line 809, in frombytes
    raise ValueError(msg)
ValueError: not enough image data
